name: 'Trigger CI'
description: 'Creates an empty commit on behalf of another user.'
inputs:
  user:
    description: 'user for which to impersonate'
    required: true
  repo-token:
    description: 'github token for creating commit'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
